apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret 
  namespace: postgre
  labels:
    app: pgsql
    type: database
type: Opaque
data:
  password: cmVkaGF0Cg==   ### this is password "redhat" generate using command echo "redhat" | openssl base64
  user: cG9zdGdyZXMK
