apiVersion: v1
kind: Pod
metadata:
  name: batch330
  labels:
    name: nginx
spec:
  containers:
  - name: batch330
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
