apiVersion: v1
kind: PersistentVolume
metadata:
  name: externalstorage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /container_storage/mysqlapp
    server: 172.31.2.23

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: externalstoragewp
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /container_storage/wordpress
    server: 172.31.2.23

