apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: prateek
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: datadb   
        ports:
        - containerPort: 3306
